#!/bin/bash

find . -print0 | xargs --null sudo chown lmangold.www-data
find . -type f -print0 | xargs --null sudo chmod 666
find . -type d -print0 | xargs --null sudo chmod 775
sudo chmod 700 set_permissions
sudo chmod 700 artisan
sudo chmod 700 vendor/bin/*

chmod 700 node_modules/.bin/*
