#!/bin/bash

find . -print0 | xargs --null sudo chown lmangold.www-data
find . -type f -print0 | xargs --null sudo chmod 666
find . -type d -print0 | xargs --null sudo chmod 775
sudo chmod 770 set_permissions
sudo chmod 770 artisan
sudo chmod 770 vendor/bin/*

chmod 770 node_modules/.bin/*
